# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ethereum_block_explorer/',
                'doc_host': 'https://Evan-Kim2028s.github.io',
                'git_url': 'https://github.com/Evan-Kim2028/ethereum_block_explorer',
                'lib_path': 'ethereum_block_explorer'},
  'syms': { 'ethereum_block_explorer.core': { 'ethereum_block_explorer.core.filter_from_address': ( 'core.html#filter_from_address',
                                                                                                    'ethereum_block_explorer/core.py'),
                                              'ethereum_block_explorer.core.filter_to_address': ( 'core.html#filter_to_address',
                                                                                                  'ethereum_block_explorer/core.py'),
                                              'ethereum_block_explorer.core.get_txs_blocks_mempool': ( 'core.html#get_txs_blocks_mempool',
                                                                                                       'ethereum_block_explorer/core.py')}}}
