# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ethereum_block_explorer/',
                'doc_host': 'https://Evan-Kim2028s.github.io',
                'git_url': 'https://github.com/Evan-Kim2028/ethereum_block_explorer',
                'lib_path': 'ethereum_block_explorer'},
  'syms': { 'ethereum_block_explorer.cryo_query': { 'ethereum_block_explorer.cryo_query.cryoQuery': ( 'cryo_query.html#cryoquery',
                                                                                                      'ethereum_block_explorer/cryo_query.py'),
                                                    'ethereum_block_explorer.cryo_query.cryoQuery._create_data_filepaths': ( 'cryo_query.html#cryoquery._create_data_filepaths',
                                                                                                                             'ethereum_block_explorer/cryo_query.py'),
                                                    'ethereum_block_explorer.cryo_query.cryoQuery.query_blocks_txs': ( 'cryo_query.html#cryoquery.query_blocks_txs',
                                                                                                                       'ethereum_block_explorer/cryo_query.py'),
                                                    'ethereum_block_explorer.cryo_query.cryoTransform': ( 'cryo_query.html#cryotransform',
                                                                                                          'ethereum_block_explorer/cryo_query.py'),
                                                    'ethereum_block_explorer.cryo_query.cryoTransform.extend_txs_blocks': ( 'cryo_query.html#cryotransform.extend_txs_blocks',
                                                                                                                            'ethereum_block_explorer/cryo_query.py')}}}
